CREATE TABLE USER_ADMIN (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE USER_INFLUENCER (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    foto_profile VARCHAR(255) DEFAULT NULL,
    link_ig VARCHAR(255) DEFAULT NULL,
    link_fb VARCHAR(255) DEFAULT NULL,
    link_tiktok VARCHAR(255) DEFAULT NULL,
    link_youtube VARCHAR(255) DEFAULT NULL,
    konten VARCHAR(255) DEFAULT NULL,
    pengenalan TEXT DEFAULT NULL,
    nomor_hp VARCHAR(15) DEFAULT NULL,
    tanggal_lahir DATE DEFAULT NULL,
    kota VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE USER_BISNIS (
    id INT(11) NOT NULL AUTO_INCREMENT,
    nama_bisnis VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    foto_profile VARCHAR(255) DEFAULT NULL,
    website VARCHAR(255) DEFAULT NULL,
    nomor_telepon VARCHAR(20) DEFAULT NULL,
    deskripsi TEXT DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE KOLABORASI (
    id INT(11) NOT NULL AUTO_INCREMENT,
    id_influencer INT(11) NOT NULL,
    id_bisnis INT(11) NOT NULL,
    detail_kolaborasi TEXT DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_influencer) REFERENCES USER_INFLUENCER (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_bisnis) REFERENCES USER_BISNIS (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
